[project]
name = "aimr"
version = "0.1.0"
description = "Generate merge request descriptions using AI models"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "GitPython>=3.1.0",
    "openai==0.28.0",
    "anthropic>=0.3.0",
]

[tool.uv]
package = true
