name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v prefix)'
        required: true
        type: string
      publish_to_pypi:
        description: 'Publish to PyPI'
        required: true
        type: boolean
        default: false
      prerelease:
        description: 'Mark as pre-release'
        required: true
        type: boolean
        default: false

permissions:
  contents: write  # Needed for creating releases
  pull-requests: write
  id-token: write
  # Add permission for code-scanning
  security-events: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        check-latest: true
        
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-release-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-release-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine check-wheel-contents
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"
    
    - name: Update version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Determine package directory from pyproject.toml
        PACKAGE_DIR=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['name'])")
        
        # Create package directory if it doesn't exist
        mkdir -p "${PACKAGE_DIR}"
        echo "__version__ = \"${{ inputs.version }}\"" > "${PACKAGE_DIR}/__init__.py"
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "${PACKAGE_DIR}/__init__.py"
        git commit -m "Bump version to ${{ inputs.version }}"
        git tag -a "v${{ inputs.version }}" -m "Release v${{ inputs.version }}"
        
        # Push both the commit and tag
        git push origin HEAD:main
        git push origin "v${{ inputs.version }}"

    - name: Build package
      run: python -m build
    
    - name: Verify package contents
      run: |
        check-wheel-contents dist/*.whl
        twine check dist/*

    - name: Generate Release Notes
      run: |
        # Get the previous tag, fallback to first commit if no tags exist
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
        
        # Generate release notes
        echo "# AIPR v${{ inputs.version }}" > release_notes.md
        echo "" >> release_notes.md
        echo "## What's Changed" >> release_notes.md
        echo "" >> release_notes.md
        
        # Get commits since last release or first commit
        git log ${PREV_TAG}..HEAD --pretty=format:"* %s" >> release_notes.md
        
        # Add installation instructions
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "" >> release_notes.md
        echo "\`\`\`bash" >> release_notes.md
        echo "# Install using pipx (recommended)" >> release_notes.md
        echo "pipx install aipr" >> release_notes.md
        echo "" >> release_notes.md
        echo "# Or install using pip" >> release_notes.md
        echo "pip install aipr" >> release_notes.md
        echo "\`\`\`" >> release_notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: release_notes.md
        files: |
          dist/*.whl
          dist/*.tar.gz
        tag_name: v${{ inputs.version }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
        fail_on_unmatched_files: true
        generate_release_notes: false
    
    - name: Check PyPI token
      if: inputs.publish_to_pypi
      run: |
        if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
          echo "Error: PYPI_API_TOKEN secret is not set"
          exit 1
        fi
    
    - name: Publish to PyPI
      if: inputs.publish_to_pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* 